version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_crud_app
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=vehicle_user
      - DB_PASSWORD=vehicle_password
      - DB_DATABASE=vehicle_crud
    depends_on:
      - db

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    container_name: vehicle_crud_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vehicle_crud
      MYSQL_USER: vehicle_user
      MYSQL_PASSWORD: vehicle_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
